### ISSUE TITLE
Fails to build on Debian 6.0

### ISSUE THREAD

**Issue by sergioramos** [agnat/node_mdns#44]
```
npm http GET https://registry.npmjs.org/mdns
npm http 304 https://registry.npmjs.org/mdns

> mdns@0.0.7 install /home/revues/mdns/node_modules/mdns
> node-gyp rebuild

make: Entering directory `/home/revues/mdns/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:
../src/mdns.hpp:15:20: warning: dns_sd.h: No such file or directory
In file included from ../src/dns_sd.cpp:4:
../src/mdns_utils.hpp:10: error: ‘DNSServiceErrorType’ was not declared in this scope
../src/mdns_utils.hpp:11: error: ‘DNSServiceErrorType’ was not declared in this scope
../src/mdns_utils.hpp:27: error: ‘DNSServiceErrorType’ has not been declared
../src/mdns_utils.hpp: In function ‘v8::Local<v8::Value> node_mdns::mdnsError(const char*, int)’:
../src/mdns_utils.hpp:29: error: ‘node_mdns::errorString’ cannot be used as a function
../src/mdns_utils.hpp: At global scope:
../src/mdns_utils.hpp:35: error: ‘DNSServiceErrorType’ has not been declared
In file included from ../src/dns_sd.cpp:5:
../src/dns_service_ref.hpp:24: error: ISO C++ forbids declaration of ‘DNSServiceRef’ with no type
../src/dns_service_ref.hpp:24: error: expected ‘;’ before ‘&’ token
../src/dns_service_ref.hpp:25: error: ‘DNSServiceRef’ has not been declared
../src/dns_service_ref.hpp:41: error: ‘DNSServiceRef’ does not name a type
In file included from ../src/dns_sd.cpp:6:
../src/txt_record_ref.hpp:22: error: ISO C++ forbids declaration of ‘TXTRecordRef’ with no type
../src/txt_record_ref.hpp:22: error: expected ‘;’ before ‘&’ token
../src/txt_record_ref.hpp:23: error: expected ‘;’ before ‘void’
../src/txt_record_ref.hpp:23: error: ‘TXTRecordRef’ has not been declared
../src/txt_record_ref.hpp:26: error: ‘TXTRecordRef’ does not name a type
../src/txt_record_ref.hpp: In member function ‘void node_mdns::TxtRecordRef::SetTxtRecordRef(int)’:
../src/txt_record_ref.hpp:23: error: ‘ref_’ was not declared in this scope
../src/dns_sd.cpp: At global scope:
../src/dns_sd.cpp:37: error: ‘v8::Handle<v8::Value> node_mdns::buildException(const v8::Arguments&)’ redeclared as different kind of symbol
../src/mdns_utils.hpp:11: error: previous declaration of ‘v8::Local<v8::Value> node_mdns::buildException’
../src/dns_sd.cpp: In function ‘void node_mdns::init(v8::Handle<v8::Object>)’:
../src/dns_sd.cpp:70: error: cannot convert ‘v8::Local<v8::Value>’ to ‘v8::Handle<v8::Value> (*)(const v8::Arguments&)’ for argument ‘3’ to ‘void node_mdns::defineFunction(v8::Handle<v8::Object>, const char*, v8::Handle<v8::Value> (*)(const v8::Arguments&))’
../src/dns_sd.cpp: In function ‘v8::Handle<v8::Value> node_mdns::buildException(const v8::Arguments&)’:
../src/dns_sd.cpp:84: error: ‘v8::Handle<v8::Value> node_mdns::buildException(const v8::Arguments&)’ redeclared as different kind of symbol
../src/mdns_utils.hpp:11: error: previous declaration of ‘v8::Local<v8::Value> node_mdns::buildException’
../src/dns_sd.cpp:93: error: ‘DNSServiceErrorType’ was not declared in this scope
../src/dns_sd.cpp:93: error: expected ‘;’ before ‘error’
../src/dns_sd.cpp:94: error: ‘error’ was not declared in this scope
../src/dns_sd.cpp: In function ‘void node_mdns::addConstants(v8::Handle<v8::Object>)’:
../src/dns_sd.cpp:100: error: ‘kDNSServiceClass_IN’ was not declared in this scope
../src/dns_sd.cpp:103: error: ‘kDNSServiceErr_NoError’ was not declared in this scope
../src/dns_sd.cpp:104: error: ‘kDNSServiceErr_Unknown’ was not declared in this scope
../src/dns_sd.cpp:105: error: ‘kDNSServiceErr_NoSuchName’ was not declared in this scope
../src/dns_sd.cpp:106: error: ‘kDNSServiceErr_NoMemory’ was not declared in this scope
../src/dns_sd.cpp:107: error: ‘kDNSServiceErr_BadParam’ was not declared in this scope
../src/dns_sd.cpp:108: error: ‘kDNSServiceErr_BadReference’ was not declared in this scope
../src/dns_sd.cpp:109: error: ‘kDNSServiceErr_BadState’ was not declared in this scope
../src/dns_sd.cpp:110: error: ‘kDNSServiceErr_BadFlags’ was not declared in this scope
../src/dns_sd.cpp:111: error: ‘kDNSServiceErr_Unsupported’ was not declared in this scope
../src/dns_sd.cpp:112: error: ‘kDNSServiceErr_NotInitialized’ was not declared in this scope
../src/dns_sd.cpp:113: error: ‘kDNSServiceErr_AlreadyRegistered’ was not declared in this scope
../src/dns_sd.cpp:114: error: ‘kDNSServiceErr_NameConflict’ was not declared in this scope
../src/dns_sd.cpp:115: error: ‘kDNSServiceErr_Invalid’ was not declared in this scope
../src/dns_sd.cpp:116: error: ‘kDNSServiceErr_Firewall’ was not declared in this scope
../src/dns_sd.cpp:117: error: ‘kDNSServiceErr_Incompatible’ was not declared in this scope
../src/dns_sd.cpp:118: error: ‘kDNSServiceErr_BadInterfaceIndex’ was not declared in this scope
../src/dns_sd.cpp:119: error: ‘kDNSServiceErr_Refused’ was not declared in this scope
../src/dns_sd.cpp:120: error: ‘kDNSServiceErr_NoSuchRecord’ was not declared in this scope
../src/dns_sd.cpp:121: error: ‘kDNSServiceErr_NoAuth’ was not declared in this scope
../src/dns_sd.cpp:122: error: ‘kDNSServiceErr_NoSuchKey’ was not declared in this scope
../src/dns_sd.cpp:123: error: ‘kDNSServiceErr_NATTraversal’ was not declared in this scope
../src/dns_sd.cpp:124: error: ‘kDNSServiceErr_DoubleNAT’ was not declared in this scope
../src/dns_sd.cpp:125: error: ‘kDNSServiceErr_BadTime’ was not declared in this scope
../src/dns_sd.cpp:152: error: ‘kDNSServiceType_A’ was not declared in this scope
../src/dns_sd.cpp:153: error: ‘kDNSServiceType_NS’ was not declared in this scope
../src/dns_sd.cpp:154: error: ‘kDNSServiceType_MD’ was not declared in this scope
../src/dns_sd.cpp:155: error: ‘kDNSServiceType_MF’ was not declared in this scope
../src/dns_sd.cpp:156: error: ‘kDNSServiceType_CNAME’ was not declared in this scope
../src/dns_sd.cpp:157: error: ‘kDNSServiceType_SOA’ was not declared in this scope
../src/dns_sd.cpp:158: error: ‘kDNSServiceType_MB’ was not declared in this scope
../src/dns_sd.cpp:159: error: ‘kDNSServiceType_MG’ was not declared in this scope
../src/dns_sd.cpp:160: error: ‘kDNSServiceType_MR’ was not declared in this scope
../src/dns_sd.cpp:161: error: ‘kDNSServiceType_NULL’ was not declared in this scope
../src/dns_sd.cpp:162: error: ‘kDNSServiceType_WKS’ was not declared in this scope
../src/dns_sd.cpp:163: error: ‘kDNSServiceType_PTR’ was not declared in this scope
../src/dns_sd.cpp:164: error: ‘kDNSServiceType_HINFO’ was not declared in this scope
../src/dns_sd.cpp:165: error: ‘kDNSServiceType_MINFO’ was not declared in this scope
../src/dns_sd.cpp:166: error: ‘kDNSServiceType_MX’ was not declared in this scope
../src/dns_sd.cpp:167: error: ‘kDNSServiceType_TXT’ was not declared in this scope
../src/dns_sd.cpp:168: error: ‘kDNSServiceType_RP’ was not declared in this scope
../src/dns_sd.cpp:169: error: ‘kDNSServiceType_AFSDB’ was not declared in this scope
../src/dns_sd.cpp:170: error: ‘kDNSServiceType_X25’ was not declared in this scope
../src/dns_sd.cpp:171: error: ‘kDNSServiceType_ISDN’ was not declared in this scope
../src/dns_sd.cpp:172: error: ‘kDNSServiceType_RT’ was not declared in this scope
../src/dns_sd.cpp:173: error: ‘kDNSServiceType_NSAP’ was not declared in this scope
../src/dns_sd.cpp:174: error: ‘kDNSServiceType_NSAP_PTR’ was not declared in this scope
../src/dns_sd.cpp:175: error: ‘kDNSServiceType_SIG’ was not declared in this scope
../src/dns_sd.cpp:176: error: ‘kDNSServiceType_KEY’ was not declared in this scope
../src/dns_sd.cpp:177: error: ‘kDNSServiceType_PX’ was not declared in this scope
../src/dns_sd.cpp:178: error: ‘kDNSServiceType_GPOS’ was not declared in this scope
../src/dns_sd.cpp:179: error: ‘kDNSServiceType_AAAA’ was not declared in this scope
../src/dns_sd.cpp:180: error: ‘kDNSServiceType_LOC’ was not declared in this scope
../src/dns_sd.cpp:181: error: ‘kDNSServiceType_NXT’ was not declared in this scope
../src/dns_sd.cpp:182: error: ‘kDNSServiceType_EID’ was not declared in this scope
../src/dns_sd.cpp:183: error: ‘kDNSServiceType_NIMLOC’ was not declared in this scope
../src/dns_sd.cpp:184: error: ‘kDNSServiceType_SRV’ was not declared in this scope
../src/dns_sd.cpp:185: error: ‘kDNSServiceType_ATMA’ was not declared in this scope
../src/dns_sd.cpp:186: error: ‘kDNSServiceType_NAPTR’ was not declared in this scope
../src/dns_sd.cpp:187: error: ‘kDNSServiceType_KX’ was not declared in this scope
../src/dns_sd.cpp:188: error: ‘kDNSServiceType_CERT’ was not declared in this scope
../src/dns_sd.cpp:189: error: ‘kDNSServiceType_A6’ was not declared in this scope
../src/dns_sd.cpp:190: error: ‘kDNSServiceType_DNAME’ was not declared in this scope
../src/dns_sd.cpp:191: error: ‘kDNSServiceType_SINK’ was not declared in this scope
../src/dns_sd.cpp:192: error: ‘kDNSServiceType_OPT’ was not declared in this scope
../src/dns_sd.cpp:241: error: ‘kDNSServiceType_TKEY’ was not declared in this scope
../src/dns_sd.cpp:242: error: ‘kDNSServiceType_TSIG’ was not declared in this scope
../src/dns_sd.cpp:243: error: ‘kDNSServiceType_IXFR’ was not declared in this scope
../src/dns_sd.cpp:244: error: ‘kDNSServiceType_AXFR’ was not declared in this scope
../src/dns_sd.cpp:245: error: ‘kDNSServiceType_MAILB’ was not declared in this scope
../src/dns_sd.cpp:246: error: ‘kDNSServiceType_MAILA’ was not declared in this scope
../src/dns_sd.cpp:247: error: ‘kDNSServiceType_ANY’ was not declared in this scope
../src/dns_sd.cpp:250: error: ‘kDNSServiceFlagsMoreComing’ was not declared in this scope
../src/dns_sd.cpp:251: error: ‘kDNSServiceFlagsAdd’ was not declared in this scope
../src/dns_sd.cpp:252: error: ‘kDNSServiceFlagsDefault’ was not declared in this scope
../src/dns_sd.cpp:253: error: ‘kDNSServiceFlagsNoAutoRename’ was not declared in this scope
../src/dns_sd.cpp:254: error: ‘kDNSServiceFlagsShared’ was not declared in this scope
../src/dns_sd.cpp:255: error: ‘kDNSServiceFlagsUnique’ was not declared in this scope
../src/dns_sd.cpp:256: error: ‘kDNSServiceFlagsBrowseDomains’ was not declared in this scope
../src/dns_sd.cpp:257: error: ‘kDNSServiceFlagsRegistrationDomains’ was not declared in this scope
../src/dns_sd.cpp:258: error: ‘kDNSServiceFlagsLongLivedQuery’ was not declared in this scope
../src/dns_sd.cpp:259: error: ‘kDNSServiceFlagsAllowRemoteQuery’ was not declared in this scope
../src/dns_sd.cpp:260: error: ‘kDNSServiceFlagsForceMulticast’ was not declared in this scope
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory `/home/revues/mdns/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:236:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Linux 3.5.2-linode45
gyp ERR! command "node" "/usr/lib/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/revues/mdns/node_modules/mdns
gyp ERR! node -v v0.8.14
gyp ERR! node-gyp -v v0.7.1
gyp ERR! not ok 
npm ERR! mdns@0.0.7 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the mdns@0.0.7 install script.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.5.2-linode45
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "mdns"
npm ERR! cwd /home/revues/mdns
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/revues/mdns/npm-debug.log
npm ERR! not ok code 0
```
