### ISSUE TITLE
cannot install mdns

### ISSUE THREAD

**Issue by nikhilbaad1** [agnat/node_mdns#229]
C:\Windows\system32>npm install mdns

> mdns@2.4.0 install C:\Windows\system32\node_modules\mdns
> node-gyp rebuild

C:\Windows\system32\node_modules\mdns>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
MSBUILD : error MSB1009: Project file does not exist.
Switch: build/binding.sln
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\system32\node_modules\mdns
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nikhi\AppData\Roaming\npm-cache\_logs\2019-04-25T12_34_47_771Z-debug.log

**Comment by agnat** [comment]
I don’t think this is an issue with node_mdns. It seems more like an issue with your tool chain. Note that node-gyp fails to create the solution file. I’d suggest to test the tool chain  by building the “node addon examples”.

**Comment by akshay20jha** [comment]
I am facing a similar issue I have installed many packages but this one is not getting installed

**Comment by marcpouliot** [comment]
Same issue. tried to build with visual studio . Fatal error C1083 . cannot open file include : 'dns_sd.h" no such file or directory.

**Comment by agnat** [comment]
https://github.com/agnat/node_mdns#installation

**Comment by Nisthar** [comment]
@agnat doesn't this library work with node v14.16.0? I am getting the same error

**Comment by Nisthar** [comment]
I tried running npm install --nodedir=/path/to/mdnsresponder. Now i am getting a new error: `common.gypi not found`

**Comment by agnat** [comment]
Works fine on mac os using node 14.16.1. Still, most likely an issue with the local tool chain...
